name: Deploy to neocities

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare source files
      run: |
        mkdir -p public
        cp -r assets       public
        cp index.html      public
        cp not_found.html  public
        cp favicon.ico     public
        cp music.html      public
        cp blogs.html      public
        cp links.html      public
        cp gallery.html    public
        cp dump.html       public

    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v2
      with:
        api_token: ${{ secrets.NEOCITIES_API_KEY }}
        cleanup: true
        dist_dir: public
